### ISSUE TITLE
Direct DSD support

### ISSUE THREAD

**Issue by ofirasp** [project-owner/peppyalsa#1]
When using the mpd.conf DoP option with “yes”:
1. The peepymeter is not working the right way because the PCM data is not really the track sound.  
2. DoP protocol not supporting 256DSD
When using DoP with “no” (which means direct DSD):
The mpd with peppyalsa thinks that the DAC is not support DSD so it converts the DSD stream to PCM on the fly and the DAC receives PCM instead of DSD.

**Comment by project-owner** [comment]
The peppyalsa plugin supports only the signal in PCM format. It would be great if there would be some ALSA plugin which could convert from DSD to PCM but as far as I know there is no such plugin in ALSA. I was recommended to use sox-dsd but I'm not sure how it could be added to the ALSA plugin chain.

**Comment by ofirasp** [comment]
Thanks !

נשלח מה-iPhone שלי

**Comment by ofirasp** [comment]
Hi,

Just wondering is if there is any way to tell the ppepyalsa to pass the direct DSD to the “real” alsa driver as “bit perfect” I understand that the  meter will not work,  but  the DAC will get the DSD and not  a concerted PCM (DoP) like  done now. 
I think that the problem is with MPD , when using the peppyalsa it thinks that it’s a DAC with no DSD direct support so it converts the stream into DoP.
So if with regular PCM the meter works and with DSD the meter will not work but the DAC will receive the direct DSD, it will be perfect.

Thanks a lot ,
Ofir.

**Comment by project-owner** [comment]
Hi,

The following recommended peppyalsa configuration "splits" the signal coming to the ALSA from the player (e.g. mpd) into two streams:
https://github.com/project-owner/peppyalsa.doc/wiki/Configuration
One stream (slave.pcm "hw:0,0") goes to the hardware/driver and the other (scopes.0 peppyalsa) to the peppyalsa itself.
I'm not sure how this configuration can change the mpd behavior.

Best regards

**Comment by project-owner** [comment]
Here is the solution suggested by Ofir:

I found a way to handle the direct DSD issue while also keeping the vu meter  running.

My solution is to configure mpd.conf with 2 Alsa devices .
One is direct to my external DSD DAC, while the other goes to peppyalsa.
In asound.conf I configured the peppyalsa slave as  my internal dac or even the pi headphones which not support did at all.

So when playing dsd file (even 256!) the mid send it to my DAC and play it as 256DSD , on the other because the other dac is not support DSD, MPD converts it to PCM on the fly, so peppy meter vu is running correctly .

mpd.conf

audio_output {
                type            "alsa"
                name            "peppyalsa"
                device          "peppyalsa"
                dop             "yes"
}
audio_output {
                type            "alsa"
                name            "alsa"
                device          "hw:5,0"
                dop             "no"
}

asound.conf

ctl.!default {
        type hw
        card 2
}

pcm.peppyalsa {
        type meter
        slave.pcm "hw:2,0"
        scopes.0 peppyalsa
}

pcm.softvol_and_peppyalsa {
        type softvol
        slave.pcm "peppyalsa"
        control {
                name "PCM"
                card 2
        }
}
